stages:
  #- test нет тестов)))))))
  - lint
  - plan-infra
  - apply-infra
  - build
  - configure-db
  - deploy-app



#test:
#  script: echo helloworld

lint-py:
  stage: lint
  image: alpine/flake8:7.3.0
  script:
    - cd code/ 
    - flake8 main.py

lint-tf: 
  stage: lint
  image: ghcr.io/terraform-linters/tflint
  script: 
    - pwd
    - cd infra/lazy_module
    - | 
      cat << EOF > .tflint.hcl
      plugin "google" {
      enabled = true
      version = "0.38.0"
      source  = "github.com/terraform-linters/tflint-ruleset-google"
      }
      EOF
    - tflint --init
    - tflint    

lint-ansible:
  stage: lint
  image: pipelinecomponents/ansible-lint:amd64-74567e9
  script: 
    - cd ansible
    - chmod 700 .
    - ansible-lint -x yaml[comments] *.yml #or changing comment's spaces by hand


terraform-plan:
  stage: plan-infra
  image: alpine/terragrunt:tf1.14.1
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"
  before_script:
    - cp $SA /tmp/credentials.json
    - export GOOGLE_APPLICATION_CREDENTIALS="/tmp/credentials.json"

  script:
    - who
    - pwd
    - mkdir ~/.ssh/
    - echo "$final_task_private" > ~/.ssh/final_task
    - echo "$final_task_pub" > ~/.ssh/final_task.pub

    

    - ls -la ~/.ssh/
    - ls -la
    - cd infra
    - echo $project_id
    - export TF_VAR_project_id=$project_id
    - terragrunt init
    - terragrunt plan
  #artifacts:
  #  paths:
  #    - ~/.ssh/final_task
  #    - ~/.ssh/final_task.pub

apply-infra:
  when: manual
  stage: apply-infra
  image: alpine/terragrunt:tf1.14.1
  needs: ["terraform-plan"] 
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  #image: hashicorp/terraform:1.14
  before_script:
    - cp $SA /tmp/credentials.json
    - export GOOGLE_APPLICATION_CREDENTIALS="/tmp/credentials.json"

  script:
    - mkdir ~/.ssh
    - echo $final_task_private > ~/.ssh/final_task
    - echo $final_task_pub > ~/.ssh/final_task.pub
    
    - chmod 600 ~/.ssh/final_task
    
    - mkdir keys
    - cp -r ~/.ssh/* ./keys
    
    - ls -la
    - ls -la keys
    - cd infra

    - export TF_VAR_project_id=$project_id
    - terragrunt init
    - terragrunt apply --auto-approve
    - terragrunt output -json > tf_output.json
    - terragrunt output -raw private-key-for-gke > ./gke-private-key.json
    - terragrunt output -raw private-key-for-registry > ./private-key.json
    - ls -la 
    - ls -la lazy_module/
    - pwd
    - echo $HOME
    - ls -la ~
    # file created -> to the next stage
  artifacts:
    #untracked: false
    #when: on_success
    #access: all
    #expire_in: "30 days"
    paths:
      - infra/tf_output.json
      - ./keys
      - infra/private-key.json
      - infra/gke-private-key.json
      

#юзать разные имеджи(ансибл терраформ) с разными стадиями

build: 
  stage: build
  image: docker:27.0
  variables:
        DOCKER_HOST: tcp://thedockerhost:2375
        DOCKER_TLS_CERTDIR: ""
  services: 
      - name: docker:27.0-dind
        alias: thedockerhost
        command: ["--tls=false"]
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "feature"
  before_script:
  #  - mkdir keys
    - mkdir ~/.ssh
  
  script:
    #- cp -r ~/.ssh/* ./keys

    - docker build -f Dockerfile_python -t europe-central2-docker.pkg.dev/valued-rigging-479120-t5/project-repo/final_python:${CI_COMMIT_SHORT_SHA} ./
    - cat infra/private-key.json | docker login --password-stdin -u _json_key_base64 https://europe-central2-docker.pkg.dev
    - docker push europe-central2-docker.pkg.dev/valued-rigging-479120-t5/project-repo/final_python:${CI_COMMIT_SHORT_SHA}
  
  artifacts:
    paths:
      #- infra/tf_output.json
      - ./keys
      #- infra/private-key.json
      - infra/lazy_module/gke-private-key.json



configure-db:
  
  stage: configure-db
  image: willhallonline/ansible:2.20.0-alpine-3.20
  when: manual
  needs: [" "]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    #- mv infra/tf_output.json ansible/
    - apk update
    - apk add jq
    - mkdir ~/.ssh
    - cp -r ./keys/* ~/.ssh
    
    - eval "$(ssh-agent -s)"
    #- cat ~/.ssh/final_task
    - echo "$final_task_private" | tr -d '\r' | ssh-add -


    - cd ansible/
    - export IP1=$(jq '.privatIps.value[0]' ../infra/tf_output.json)
    - "sed -i '6 s/#*ansible_host.*/ansible_host: '$IP1'/' inventory.yml"
    -  export IP2=$(jq '.privatIps.value[1]' ../infra/tf_output.json)
    - "sed -i '11 s/#*ansible_host.*/ansible_host: '$IP2'/' inventory.yml"
    
    - export ANSIBLE_CONFIG="./ansible.cfg"

    - ansible-playbook -Kvv -i inventory.yml playbooks/vm-initialization.yml 
    #ansible_become_pass=$SECRET PASS
  artifacts:
      paths:
        - infra/gke-private-key.json

deploy-app:
  image: google/cloud-sdk:543.0.0-alpine
  stage: deploy-app
  when: manual
  needs: ["configure-db"]
  rules:
   - if: $CI_PIPELINE_SOURCE == "merge_request_event"
   - if: $CI_COMMIT_BRANCH == "master"
   # - if:  $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
  
  before_script: 
    #- cat infra/gke-private-key.json | docker login -u _json_key --password-stdin https://eu.gcr.io
    #- docker-credential-gcloud --project $project_id --access-token-file infra/gke-private-key.json 
    - apk add helm
  script:
    #- gcloud auth activate-service-account artifact-registry-account@valued-rigging-479120-t5.iam.gserviceaccount.com --key-file=infra/private-key.json
    #- gcloud auth configure-docker europe-central2-docker.pkg.dev
    


    - cat infra/gke-private-key.json    
    - gcloud auth activate-service-account  --key-file=infra/gke-private-key.json
    # попробовать логиниться и не логиниться, вроде создаются под капотом node pool аккаунты и образ сам стягивается из регистри

    - gcloud config set project $project_id
    - gcloud config set container/cluster main-k8s-cluster
    - gcloud config set compute/zone eu-central1-b
    - gcloud container clusters get-credentials  main-k8s-cluster --zone europe-central2-a --project $project_id
    - gcloud components install kubectl

    - kubectl create namespace final-task-inno --dry-run=client -o json | kubectl apply -f -

    - | 
      kubectl create secret -n final-task-inno docker-registry docker-secret \
      --docker-server=europe-central2-docker.pkg.dev \
      --docker-username=_json_key_base64  \
      --docker-password=${DOCKER_PODS_PASSWORD} \
      --dry-run=client -o json | kubectl apply -f -


    - |
      kubectl create secret -n final-task-inno generic secret-for-python \
      --from-literal=pg_pass=${pg_pass} \
      --from-literal=pg_db=${pg_db} \
      --from-literal=pg_url=${pg_url} \
      --from-literal=postgres_password=${postgres_password} \
      --dry-run=client -o json | kubectl apply -f -

    - kubectl get secrets -n final-task-inno
    
    
    - helm upgrade --install --atomic python-app-chart ./k8s/main-chart --set image.tag="final_python:${CI_COMMIT_SHORT_SHA}"
    
    #пропатчить черед sed

  
  