##SPDX-License-Identifier: MIT-0
#---
## tasks file for deploy_db
- name: Debug variables
  ansible.builtin.debug:
    msg: 
      - "Password is: {{ db_password }}"
      - "Hash is: {{ commit_hash }}"
- name: settings.01 - Add primary user
  user:
     name: "{{ primary_user }}"
     system: yes
     state: present
     shell: /bin/bash
     home: "/home/{{ primary_user }}"
     password: "{{db_password}}"

- name: settings.02 - Allow primary user to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "'^{{ primary_user }}'"
    line: "{{ primary_user }} ALL=(ALL) NOPASSWD: ALL"

- name: settings.03 - Allow postgresql passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "'^postgres'"
    line: "postgresql ALL=(ALL) NOPASSWD: ALL"


#- name: Add replication_user 
#  user:
#     name: replication_user
#     system: yes
#     state: present
#     shell: /bin/bash
#     home: "/home/replication_user"

- name: Add app_user #нужно создать юзера в системе или в самой бд 
  user:
     name: app_user
     system: yes
     state: present
     shell: /bin/bash
     home: "/home/app_user"


- name: "postgresql.01 - install db + python"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  become: true
  vars:
    packages:
    - postgresql
    #- python3-pip
    - python3-psycopg2

- name: postgre.01.1 - Making sure db is up
  ansible.builtin.systemd_service:
    state: started
    name: postgresql


- name: "postgresql.02 - update - WAL_LEVEL and Listes_adress "
  ansible.builtin.lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf #нужно будет менять   15   при другой версии postgre   
    state: present
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  loop: "{{ lines }}"
  vars:
    lines:
      - {regexp: "#wal_level", line: "wal_level = logical" }  
      - {regexp: '#listen_addresses', line: "listen_addresses = '*'" }  
      - {regexp: '#hot_standby', line: "hot_standby = on" }  



- name: "postgresql.03 - update -  pg_hba.conf "
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/16/main/pg_hba.conf
    contype: host
    users: '{{ item.user }}'
    source: '{{ item.source }}'
    databases: '{{item.database}}'
    method: md5
    create: true
    state: present
  loop: "{{lines}}"
  vars:
    lines:
    - { source: "10.10.0.0/20", database: all, user: replication_user }
    - { source: "10.10.0.0/20", database: replication, user: replication_user }
    - { source: "10.4.0.0/16", database: all, user: replication_user}
    - { source: "10.4.0.0/16", database: replication, user: replication_user }
    - { source: "10.10.0.0/20", database: all, user: postgres }
    - { source: "10.10.0.0/20", database: all, user: all }

  #notify:                #isnt working
  #  - Restart postgresql  
  
- name: postgre.04 - Making sure db is restarted
  ansible.builtin.systemd_service:
    state: restarted
    name: postgresql

- name: "postgresql.05 - create db"
  community.postgresql.postgresql_db:
    name: "{{db_name}}"
    comment: My test DB
    #owner: replication_user
    state: present
  become_user: postgres
 
- name: settings.06 - create replication_user  
  community.postgresql.postgresql_user:
    login_db: "{{db_name}}"
    name: replication_user
    password: "{{ db_password }}" #закинуть пароль в vault
    role_attr_flags: REPLICATION #
    state: present
  become_user: postgres


- name: settings.06-2 - update postgres  
  community.postgresql.postgresql_user:
    login_db: "postgres"
    name: postgres
    password: "{{postgres_password}}" #закинуть пароль в vault
    state: present
  become_user: postgres


- name: "postgresql.07 - swich user db"
  community.postgresql.postgresql_db:
    name: "{{db_name}}"
    comment: My test DB
    owner: postgres
    #owner: replication_user
    state: present
  become_user: postgres


- name: postgresql.08 - Create a new publication with name "publication1" targeting all tables in database "{{db_name}}"
  community.postgresql.postgresql_publication:
    login_db: "{{db_name}}"
    name: publication1
    comment: Made by Ansible
    login_user: postgres 
    state: present #добавил в ласт трае
  become_user: postgres #?
  #become_user: replication_user #?
  #become: true