{{- if .Values.dockerSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  namespace: final-task-inno
type: kubernetes.io/dockercfgjson
data:
  .dockercfg: | 
    {{- .Values.dockerSecret.data | nindent 6}}
{{- end}}