{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  namespace: final-task-inno
  name: secret-for-python
type: Opaque

stringData:
{{- range $key, $value :=  .Values.secret.stringData }}
  {{ $key }}: {{$value}}
{{- end }}

{{- end}}
#--------------------

#PG_PASS=1234
#PG_URL=pg-primary:5432
#DB_NAME=gc_cloud
#  

#будут генериться в пайплайне