- name: "db-preparing-primary"
  hosts: all
  gather_facts: true
  become: true
  handlers: []
  collections:
  - community.docker
  
  roles: 
    - { role: deploy_db_primary, when: inventory_hostname == "pg-primary" }
    - { role: deploy_db_standby, when: inventory_hostname == "pg-standby" }
  vars_files:
    - secrets.yml