- name: "filebeat.01 - copy"
  ansible.builtin.copy:
    src: ~/infrastructure/elastic/filebeat-8.5.3-amd64.deb
    dest: /tmp/filebeat.deb
    mode: "644"
- name: "filebeat.02 - unpack"
  ansible.builtin.apt:
    deb: /tmp/filebeat.deb
    state: present
- name: "filebeat.01.1 - copy" 
  ansible.builtin.copy:
    src: ~/infrastructure/elastic/filebeat.yml
    dest: /etc/filebeat/filebeat.yml #??? 
    mode: "644"


#---------test------------------
- name: "filebeat.01.2 - copy certs" 
  ansible.builtin.copy:
    src: ~/infrastructure/elastic/certs
    dest: /etc/filebeat/ #??? 
    mode: "644"
#---------test---------------------


- name: "filebeat.03 - ensuring service is ok"
  ansible.builtin.service:
    name: filebeat
    state: restarted
    enabled: yes
